getformat.c
holberton.h

Fixes #4 
Get the character after the % to compare format

[Feature] get the character after the %

---

_printf.c

Fixes #9 
Format to printf Given

Give starting template to printf

---

.gitignore
_printf.c
getformat.c
holberton.h
main.c
printchar.c

Fixes #8 
Fix compilation errors on other files

[Fix] Compilation Fixes

---

getformat.c
printchar.c

Fixes #8 
print characters and fix on getformat to not print 0

[Feature][Fix] printchar & Fix test on getformat

---

_printf.c
getformat.c
holberton.h
test/18-main.c

Fixes #18 
Prints the remaining characters with no % on format and gets the position i on _printf from getformat

[Feature] No struct but works to print remaining string and get position

---

_printf.c
getfunction.c
holberton.h
printchar.c

Fixes #22 
Added parameters to functions and changed prototypes, added at _printf parameter to count  bytes printed

[Fixes] Functions to get new parameters and logic order on holberton

---

_printf.c
getformat.c
getfunction.c
holberton.h
test/12-main.c
test/main.c

Fixes #25 
Create option structure

[fixes] return operation type on getformat useit in printf

---

test/testbash

#29
Create script to generate test and execute

[feature] add test executable

---

_printf.c
getfunction.c
holberton.h

prepare files to test checkers

Jm#fixesbetty

---

printchar.c
test/testflahbash

bash with all flags resolve conflicts

[Fixes] void unused parammeter and create bash with all flags

---

_printf.c
getfunction.c
test/27-main.c

Fixes #27 
validate numbers of bytes written

[Fixes] validates number of bytes writen

---

_putchar.c
getformat.c

delete unussed variable

---

printchar.c

Fixes #37
removed printf error on printchar

[Fixes] Removed Error on printchar

---

printchar.c

Fixes #40 
prints nothing on null char

[Fixes]added condition to not write when p is null

---

_printf.c
getfunction.c
test/39-main.c
test/41-main.c

Fixes #41 
Fixes #39 
Solve bugs

[Fixes] no print %

---

printchar.c

On printchar added the options from 7 to 13

[Fixes] added special characters to be printeable on char format

---

_printf.c

On printf(NULL) prints nothing

[Fixes]no print on null

---

_printf.c
printchar.c
test/39-main.c
test/main.c

Fixes #47 
Return -1 on %only, character null and format null
resolved 40 lines on betty

[Fixes] Return -1 on wrong inputs and betty on printf

---

getfunction.c
printchar.c

[change] fixes betty style code

---

getformat.c
printchar.c

add description to putchar.c

---

printchar.c

Fixes #40 
Return 1 and print then null on %c '\0'

[Fixes] print the null and return 1

---

getfunction.c
number_to_string.c

Fixes #52 
handle NULL after call malloc

[Fixes] check malloc

---

getfunction.c

[fixes] declate bytes befor void casting

---

man_3_printf
man_page

Fixes #26 
Fixed man page name and improved

[Fixes] Man with proper name
